# Dependabot configuration for automated dependency updates
# This enables automated security updates and dependency management
# Reference: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "terragon-labs/core-team"
    assignees:
      - "terragon-labs/security-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "langchain*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
    groups:
      testing-dependencies:
        patterns:
          - "pytest*"
          - "coverage*"
          - "factory-boy"
          - "httpx"
      linting-dependencies:
        patterns:
          - "ruff"
          - "black"
          - "isort"
          - "mypy"
      security-dependencies:
        patterns:
          - "bandit*"
          - "safety"
          - "cryptography"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "terragon-labs/devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci-cd"
      - "github-actions"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    reviewers:
      - "terragon-labs/infrastructure-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "infrastructure"