global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'startup-studio-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics'

  - job_name: 'pipeline-services'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['host.docker.internal:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['host.docker.internal:9121']
    scrape_interval: 30s