{
 "title": "Token Usage",
 "description": "RPS by Token",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "api.node.glif.io",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(log_metric_counter_authorized_requests{host=\"api.node.glif.io\"}[$__rate_interval])) by (token)",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "calibration-archive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(log_metric_counter_authorized_requests{host=\"calibration.node.glif.io\", request=~\"POST /archive/lotus/.*\"}[$__rate_interval])) by (token)",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "fvm-archive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(log_metric_counter_authorized_requests{host=\"node.glif.io\", request=~\"POST /fvm-archive/lotus/.*\"}[$__rate_interval])) by (token)",
     "legendFormat": "{{token}}"
    }
   ]
  }
 ]
}