apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: agentic-startup-studio
  labels:
    app.kubernetes.io/name: agentic-startup-studio
    app.kubernetes.io/component: config
data:
  # Application configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  # AI/ML Configuration
  MAX_CONCURRENT_AGENTS: "5"
  DEFAULT_MODEL: "gpt-4"
  TOKEN_BUDGET_LIMIT: "100000"
  
  # Database configuration (non-sensitive)
  DATABASE_HOST: "postgresql-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "startup_studio"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Observability configuration
  OTEL_SERVICE_NAME: "agentic-startup-studio"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger-collector:4317"
  PROMETHEUS_METRICS_PORT: "8090"
  
  # API configuration
  API_PORT: "8080"
  API_HOST: "0.0.0.0"
  CORS_ORIGINS: "https://terragon.ai,https://*.terragon.ai"
  
  # Feature flags
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  ENABLE_HEALTH_CHECKS: "true"
  ENABLE_RATE_LIMITING: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: agentic-startup-studio-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: config
data:
  # Prometheus configuration
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'agentic-startup-studio'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - agentic-startup-studio
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true