apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: agentic-startup-studio
  labels:
    app.kubernetes.io/name: agentic-startup-studio
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # AI API Keys (will be populated via external-secrets or sealed-secrets)
  OPENAI_API_KEY: "placeholder-will-be-replaced"
  ANTHROPIC_API_KEY: "placeholder-will-be-replaced"
  
  # Database credentials
  DATABASE_PASSWORD: "placeholder-will-be-replaced"
  DATABASE_URL: "postgresql://postgres:placeholder-will-be-replaced@postgresql-service:5432/startup_studio"
  
  # JWT configuration
  JWT_SECRET_KEY: "placeholder-will-be-replaced"
  JWT_ALGORITHM: "HS256"
  
  # External service credentials
  GITHUB_TOKEN: "placeholder-will-be-replaced"
  GOOGLE_ADS_API_KEY: "placeholder-will-be-replaced"
  
  # Encryption keys
  ENCRYPTION_KEY: "placeholder-will-be-replaced"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: agentic-startup-studio
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "placeholder-will-be-replaced"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "startup_studio"
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: agentic-startup-studio-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Grafana admin credentials
  GF_SECURITY_ADMIN_PASSWORD: "placeholder-will-be-replaced"
  
  # Alertmanager configuration
  SLACK_API_URL: "placeholder-will-be-replaced"
  PAGERDUTY_INTEGRATION_KEY: "placeholder-will-be-replaced"