name: Python CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # As per DEVELOPMENT_PLAN.md

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest # Assuming these will be used for linting and testing
        # In the future, this step should install from a requirements.txt or pyproject.toml
        # For example: pip install -r requirements.txt

    - name: Lint with Ruff
      run: |
        ruff check .

    - name: Run Pytests
      run: |
        pytest
        # This command assumes tests are discoverable by pytest by default.
        # If tests are in a specific directory, e.g., 'tests/', use 'pytest tests/'
        # Add any necessary pytest options here.
